openapi: 3.0.0
info:
  title: Örnek REST API
  description: Bu API, örnek veriler üzerinde CRUD işlemlerini gerçekleştirir.
  version: 1.0.0

paths:
  /items:
    get:
      summary: Tüm öğeleri listele
      responses:
        '200':
          description: Başarılı yanıt, tüm öğeleri içerir.
    post:
      summary: Yeni bir öğe oluştur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Oluşturulan öğe başarıyla eklendi.
    delete:
      summary: Tüm öğeleri sil
      responses:
        '204':
          description: Tüm öğeler başarıyla silindi.

  /items/{id}:
    get:
      summary: Belirli bir öğeyi al
      parameters:
        - in: path
          name: id
          required: true
          description: Alınacak öğenin ID'si
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Başarılı yanıt, belirtilen öğeyi içerir.
        '404':
          description: Öğe bulunamadı.
    put:
      summary: Belirli bir öğeyi güncelle
      parameters:
        - in: path
          name: id
          required: true
          description: Güncellenecek öğenin ID'si
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Öğe başarıyla güncellendi.
        '404':
          description: Öğe bulunamadı.
    delete:
      summary: Belirli bir öğeyi sil
      parameters:
        - in: path
          name: id
          required: true
          description: Silinecek öğenin ID'si
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Öğe başarıyla silindi.

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
